### ISSUE TITLE
Add retext-usage

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-hemingway#8]
Add retext-usage support:

https://github.com/adamhollett/retext-usage

**Comment by MasterTuto** [comment]
There is an error:

https://github.com/adamhollett/retext-usage/issues/4

**Comment by AdrianSimionov** [comment]
This https://github.com/kostasx/retext-usage/commit/612d0ccf75e7734840a28530237b6cf6f1e8dbb9 does not help? Can we fix this one ourselves and incorporate the fix here?
