### ISSUE TITLE
Add retext-overuse

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-hemingway#9]
Add retext-overuse support:

https://github.com/dunckr/retext-overuse

**Comment by MasterTuto** [comment]
It come up with this error:

https://github.com/dunckr/retext-overuse/issues/6

**Comment by AdrianSimionov** [comment]
Can we fix this ourselves and use the fix in our code?

**Comment by MasterTuto** [comment]
Actually, I have already fixed, but I don't know if obsidian devs would accept it. I though of a way after I commented that issue.
